### ISSUE TITLE
Select project management/collaboration tools

### ISSUE THREAD

**Issue by nicklafarge** [mbd-astro/forest#15]
## Checklist

- [ ] Set Up Wiki
   - [x] Create page
   - [x] Link/describe the basic tools
   - [ ] Add code standards/resources
- [ ]  User guide
   - [ ] Select the form/platform/template of the user guide
   - [ ] Learn how code documentation can sync with guide
   - [ ] Create basic version
- [x] Create GitHub Project
- [x] Decide on discussion boards/announcements
- [x] Basic Issue tags/milestone organization

## Some Notes so far:

Current plan is to use the [Forest GitHub Project](https://github.com/orgs/mbd-astro/projects/3/views/2?groupedBy%5BcolumnId%5D=Milestone) to keep track of issues, tasks, and to organize milestones 

- For now issues are public in the GitHub repo, but the project itself is private (new users must be added to both the organization and project)
- Labels can help identify current tasks that anyone who wishes can contribute to - let's try to use [help wanted](https://github.com/mbd-astro/forest/labels/help%20wanted) and [good first issue](https://github.com/mbd-astro/forest/labels/good%20first%20issue) to tag those
- Milestones identify task priorities for when we anticipate incorporating into the project
- We can create several Views in the Project to keep track of tasks. Converting project items to issues is helpful for items that are associated with a particular milestone. These Views also support kanban boards, which may be helpful for tracking progress of individual items.
- The "prototype built" status is intended to indicate that I have a working prototype for that component (obviously subject to changes/updates as we build the real version of this project)

Discussions unrelated to specific issues can occur within the GitHub discussions page on the forest repository
- Teams are listed at [https://github.com/mbd-astro/forest/discussions](https://github.com/mbd-astro/forest/discussions) 

[The wiki](https://github.com/mbd-astro/forest/wiki) will be used to keep track of helpful resources for developers (not users!)
- For example: resources for learning C++, coding conventions, git workflow etc
- The wiki should be kept separate from the user-facing documentation
- need to clarify what goes in the wiki, and what goes in the user guide (see #7 )

Development meta discussions/"announcements" will occur in [forest-developers](https://github.com/orgs/mbd-astro/teams/forest-developers) team page.

**Comment by nicklafarge** [comment]
@rjpower4 Did you create a forest developer team? I thought I saw that in an email, but don't see it listed on the page.

**Comment by nicklafarge** [comment]
Also @rjpower4 What do you think about this overall workflow that keeps everything within the GitHub ecosystem? Do you see anything missing from here?

**Comment by rjpower4** [comment]
Couple of notes: 

- I don't think we should attach version numbers to the milestones other than v1.0.0 as this conflates two levels of semantic meaning: high-level associated with project goals and a lower-level version associated with features added/APIs broken
- I have created a "leads" team, it is [here](https://github.com/orgs/mbd-astro/teams/forest-leads), do you want a general developer team? 
- I would advise doing general discussions in [discussions](https://github.com/mbd-astro/forest/discussions)
- Announcements for the developer team could go in that lower-level team if we want or put them in discussions

**Comment by nicklafarge** [comment]
> * I don't think we should attach version numbers to the milestones other than v1.0.0 as this conflates two levels of semantic meaning: high-level associated with project goals and a lower-level version associated with features added/APIs broken

Maybe this isn't a great motivation, but I added numbers in because grouping by milestone on the GitHub Projects page occurs alphabetically, and I wanted it in that chronological order to keep track of things - so putting numbers in clarifies what order they go in. I agree it's a bit awkward. I can look into if any other options work for the management side of things.

**Comment by nicklafarge** [comment]
Having a general developers team I think is a good idea so we can put announcements and whatnot there, separate from the discussions board

**Comment by rjpower4** [comment]
> > * I don't think we should attach version numbers to the milestones other than v1.0.0 as this conflates two levels of semantic meaning: high-level associated with project goals and a lower-level version associated with features added/APIs broken
> 
> Maybe this isn't a great motivation, but I added numbers in because grouping by milestone on the GitHub Projects page occurs alphabetically, and I wanted it in that chronological order to keep track of things - so putting numbers in clarifies what order they go in. I agree it's a bit awkward. I can look into if any other options work for the management side of things.

Maybe just number them?

**Comment by nicklafarge** [comment]
> Maybe just number them?

Done. Does that work for you?

**Comment by rjpower4** [comment]
That makes me much happier 🔥

**Comment by nicklafarge** [comment]
Since this is mostly done now, I'm going to move the remaining items into separate issues
